%YAML:1.0
annotators:
    - CollectionReader
    - ImagePreprocessor
    - RegionFilter
    - NormalEstimator
    - PlaneAnnotator
    - PointCloudClusterExtractor
    - ImageSegmentationAnnotator
    - ClusterMerger
    - Cluster3DGeometryAnnotator
    - PrimitiveShapeAnnotator
    - ClusterColorHistogramCalculator
    - ObjectIdentityResolution
    - StorageWriter
